[lowlevelapi]
enable = true
# Time in seconds between Low-level API packets before control program
# disables robot
timeout = 0.05
# Port for incoming and outgoing Low-level API communications.
# Change if these settings interfere with any other programs or network
# Traffic on the payload computer. Must match settings in lowlevelapi.c
# (lines 181 and 183). These should not be changed under normal operation
listen-port = 25500
send-port = 25501

# Define 1 kg box with an AprilTag on the front of the box
[world.package.body]
type = "box"
size = [0.4, 0.4, 0.4]
mass = 1.0
april-tags = [{id = 0, pose = {xy = [0.2, 0.0]}}]

# Define a table with two AprilTags on the front of the table
[world.table.body]
type = "box"
size = [0.4, 1.0, 0.05]
april-tags = [{id = 1, pose = {xy = [0.2, -0.5]}},
            {id = 2, pose = {xy = [0.2, 0.5]}}]

# Add robot to world
[[model-list]]
model = "robot"
pose = {xyz = [0, 0, 1]}

# Add table in front of the robot and rotate so the AprilTags are facing the robot.
[[model-list]]
model = "table"
pose = {rpyxyzd = [0, 0, 180, 1.5, 0, 0.0]}
fixed = true

# Add another table behind the robot. Set the AprilTag ID offset so the AprilTag IDs don't conflict.
[[model-list]]
model = "table"
pose = {xyz = [-1.5, 0, 0.0]}
april-tag-id-offset = 10
fixed = true

# Add box on top of table in front of the robot.
[[model-list]]
model = "package"
pose = {rpyxyzd = [0, 0, 180, 1.5, 0, 0.01]}
